config/routes.rb
Blogger::Application.routes.draw do

  get "static_pages/index"

  root to: 'static_pages#index'

  devise_for :authors

  resources :authors do
    member do
      delete 'remove_article_from_author'
      delete 'remove_tag_from_author'
    end
  end

  get "tags/index"

  get "tags/show"

  resources :articles do
    member do
      put 'add_article_to_author'
    end
  end 

  resources :comments

  resources :tags do
    member do
      put 'add_tag_to_author'
    end
  end
  

  

end

app/models/article.rb
class Article < ActiveRecord::Base
  attr_accessible :title, :body, :tag_list, :image

  has_many :comments

  has_many :taggings
  has_many :tags, through: :taggings

  has_many :authors, through: :article_stores
  has_many :article_stores

  belongs_to :author

  has_attached_file :image, styles: { medium: "300x300>", thumb: "100x100>" }

  def tag_list
	  self.tags.collect do |tag|
	    tag.name
	  end.join(", ")
	end

	def tag_list=(tags_string)
		self.taggings.destroy_all
		
		tag_names = tags_string.split(',').collect { |s| s.strip.downcase }.uniq

		tag_names.each do |tag_name|
			tag = Tag.find_or_create_by_name(tag_name)
			tagging = self.taggings.new
			tagging.tag_id = tag.id
		end
	end

	def create_new_article_store
		self.article_stores.build
	end
end

app/models/article_store.rb
class ArticleStore < ActiveRecord::Base
  attr_accessible :article_id, :author_id

  belongs_to :article
  belongs_to :author
end

app/models/author.rb
class Author < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me, :name

  has_many :articles, through: :article_stores
	has_many :article_stores
  
  has_many :tags, through: :tag_stores
  has_many :tag_stores
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  attr_accessible :article_id, :author_name, :body

 	belongs_to :article
end

app/models/tag.rb
class Tag < ActiveRecord::Base
  attr_accessible :name

  has_many :taggings, dependent: :destroy
  has_many :articles, through: :taggings

  has_many :authors, through: :tag_stores
  has_many :tag_stores

  def to_s
  	name
  end

  def create_new_tag_store
  	self.tag_stores.build
  end
end

app/models/tag_store.rb
class TagStore < ActiveRecord::Base
  attr_accessible :author_id, :tag_id

  belongs_to :author
  belongs_to :tag
end

app/models/tagging.rb
class Tagging < ActiveRecord::Base
  attr_accessible :article_id, :tag_id

  belongs_to :article
  belongs_to :tag
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

	before_filter :authenticate_author!, except: [:index, :show]

	def index
		@articles = Article.all
	end

	def show
		@article = Article.find(params[:id])
		@comment = Comment.new
		@comment.article_id = @article.id
	end

	def new
		@article = Article.new
	end

	def create
		@article = Article.new(params[:article])
		@article.author_id = current_author.id
		article_author_association
		if @article.save
			redirect_to article_path(@article), notice: "Article successfully created...!!!!"
		end
	end

	def edit
		@article = Article.find(params[:id])
	end

	def destroy
		@article = Article.find(params[:id])
		@article.destroy
		redirect_to articles_path, notice: "Article successfully destroyed...!!!"
	end

	def update
		@article = Article.find(params[:id])
		if @article.update_attributes(params[:article])
			flash.notice = "Article, '#{@article.title}' has been	 successfully updated...!!!"
			redirect_to article_path(@article)
		end
	end

	def add_article_to_author
		@article = Article.find(params[:id])
		article_author_association
		if @article.save
			redirect_to articles_path
		end
	end

	def remove_article_from_author
		store = Article.article_stores.where(author_id: current_author.id)
	end

	private

		def article_author_association
			store = @article.create_new_article_store
			store.author_id = current_author.id
		end
end

app/controllers/authors_controller.rb
class AuthorsController < ApplicationController
  def show
    @author = Author.find(params[:id])
  end

  def index
    @authors = Author.all
  end

  def create
  end

  def destroy
    @author = Author.find(params[:id])
    @author.destroy
    redirect_to root_path
  end

  def edit
  end

  def remove_article_from_author
    ArticleStore.find_by_author_id_and_article_id(current_author.id, params[:id]).destroy
    redirect_to author_path(current_author)
  end

  def remove_tag_from_author
    TagStore.find_by_author_id_and_tag_id(current_author.id, params[:id]).destroy
    redirect_to author_path(current_author)
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

	def create
		@comment = Comment.new(params[:comment])
		@comment.save

		redirect_to	article_path(@comment.article)
	end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def index
  end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  def index
  	@tags = Tag.all
  end

  def show
  	  @tag = Tag.find(params[:id])
  end

  def destroy
  	@tag = Tag.find(params[:id])
  	@tag.destroy
  	redirect_to tags_path, notice: "Tag successfully deleted...!!!"
  end

  def add_tag_to_author
    @tag = Tag.find(params[:id])
    store = @tag.create_new_tag_store
    store.author_id = current_author.id
    if @tag.save
      redirect_to tags_path
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper

	def tag_links(tags)
		links = tags.collect { |tag| link_to tag.name, tag_path(tag), class: "tags" }
		return links.join(" ").html_safe
	end
end

app/helpers/authors_helper.rb
module AuthorsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/views/articles/_comment.html.erb
<% @article.comments.each do |comment| %>
	<div class="comment">
	  <p><%= comment.author_name %> says:</p>
	  <h4>"<%= comment.body %>."</h4>
	  <p>Posted <%= distance_of_time_in_words(comment.article.created_at, comment.created_at) %> later</p>
	</div>	
<%end%>

app/views/articles/_form.html.erb
<%= form_for(@article, html: { multipart: true }) do |f| %>
	<ul>
		<% @article.errors.full_messages.each do |error| %>
	    <li><%= error %></li>
	  <% end %>
	</ul>

	<p>
		<%= f.label :title %>
		<%= f.text_field :title %>
	</p>

	<p>
		<%= f.label :body %>
		<%= f.text_area :body %>
	</p>

	<p>
	  <%= f.label :tag_list %><br />
	  <%= f.text_field :tag_list %>
	</p>

	<p>
	  <% if @article.image.exists? %>
	      <%= image_tag @article.image.url %><br/>
	  <% end %>
	  <%= f.label :image, "Attach a New Image" %><br />
	  <%= f.file_field :image %>
	</p>


	<p>
		<%= f.submit %>
	</p>
<% end %>

app/views/articles/edit.html.erb
<h1>Edit an Article</h1>

<%= render 'form' %>

app/views/articles/index.html.erb
<h1>Listing all articles</h1>
<div class = "article_list">
	<table>
		<% @articles.each do |article| %>
			<tr class = "article_row">
				<td style="padding: 5px"><h3 class = "article_name"><%= link_to article.title, article_path(article), class: 'article_title',id: "article_#{article.id}" %></h3>
					<div style = "margin-bottom: 10px;"><%= tag_links(article.tags) %></div></td>
				<% if author_signed_in? %>
					<% if article.author_id == current_author.id %>
						<td><p class="add_tag">PERSONAL</p></td>
					<% else %>
						<td>	
							<% unless article.authors.include?(current_author)  %>
								<%= button_to "Add", { action: "add_article_to_author", id: article.id }, method: :put %>
							<% else %>
								<p class="add_tag">Added</p>
							<% end %>
						</td>
					<% end %> 
					<% if current_author.admin? %>
							<td ><%= button_to "Delete", { :action => "destroy", :id => article.id },
																				 :confirm => "Are you sure?", method: :delete %></td>
					<% end %>
				<% end %>
			</tr>
		<% end %>
	</table>
</div>

<%= link_to "Create new aricle", new_article_path, class: 'new_article' %>

app/views/articles/new.html.erb
<h1>Create a New Article</h1>

<%= render 'form' %>

app/views/articles/show.html.erb
<h1><%= @article.title %></h1>

<p>Tags: <%= tag_links(@article.tags) %></p>
<br />

<% if @article.image.exists? %>
	<p><%= image_tag @article.image.url %><p><br/>
<% end %>

<p><%= @article.body %></p>
<br />
<% if author_signed_in? %>
	<% if @article.author_id == current_author.id || current_author.admin? %>
		<div class = "button">
			<%= link_to "Edit", { :action => "edit", :id => @article.id }, method: :get %>
			<%= link_to "Delete", { :action => "destroy", :id => @article.id },
		    												:confirm => "Are you sure?", method: :delete %>
		</div>
	<% end %>
<% end %>

<hr>


</br>

<h3>Comments (<%= @article.comments.count %>)</h3>
<%= render "comment" %>

<%= render 'comments/form' %>

app/views/authors/create.html.haml
%h1 Authors#create
%p Find me in app/views/authors/create.html.haml

app/views/authors/destroy.html.haml
%h1 Authors#destroy
%p Find me in app/views/authors/destroy.html.haml

app/views/authors/edit.html.haml
%h1 Authors#edit
%p Find me in app/views/authors/edit.html.haml

app/views/authors/index.html.haml
%h1 Authors

%table
	- @authors.each do |author|
		%tr
			%td
				%h2
					= link_to author.name, author_path(author)
			- if current_author.admin? && author != current_author
				%td
					=button_to "Delete", author_path(author), method: :delete


	

app/views/authors/show.html.haml
%h1
	= @author.name

- unless current_author.admin? || @author != current_author
	= link_to "Delete Account", author_path(@author), method: :delete, style: "float: right", confirm: "Are you sure ?"

%table.author_article_list
	%thead
		%tr
			%th
				%h2 Articles
	%tbody
		- @author.articles.each do |article|
			%tr
				%td
					= link_to article.title, article_path(article)
					= link_to "Remove", {  action: "remove_article_from_author", id: article.id }, method: :delete , style: "float:right; border-radius: 5px; background-color: #6C7C9A; margin-bottom: 2px; color: white; padding: 5px;"
%table.author_tag_list
	%thead
		%tr
			%th
				%h2 Tags
	%tbody
		- @author.tags.each do |tag|
			%tr
				%td
					= link_to tag.name, tag_path(tag)
					= link_to "Remove", {  action: "remove_tag_from_author", id: tag.id }, method: :delete , style: "float:right; border-radius: 5px; background-color: #6C7C9A; margin-bottom: 2px; color: white; padding: 5px;"

app/views/comments/_form.html.erb
<h3>Post a Comment</h3>

<%= form_for @comment do |f| %>
  <%= f.hidden_field :article_id %>
  <p>
    <%= f.label :author_name, 'Your Name' %><br/>
    <%= f.text_field :author_name %>
  </p>
  <p>
    <%= f.label :body, 'Your comment' %><br/>
    <%= f.text_area :body %>
  </p>
  <p>
    <%= f.submit 'Submit' %>
  </p>
<% end %>

app/views/layouts/application.html.haml
!!!
%html
	%head
		%title Blogger
		= stylesheet_link_tag    "application"
		= javascript_include_tag "application"
		= csrf_meta_tags
	
	%body
		%nav
			%ul
				%li
					= link_to "Home", root_path
				%li 
					= link_to "Articles", articles_path
				%li 
					= link_to "Tags", tags_path
				- if author_signed_in?
					%li
						= link_to "Authors", authors_path
					%li
						= link_to "Profile", author_path(current_author)
					%li		
						= link_to "Log out", destroy_author_session_path, method: :delete
					%li.author_name
						= "Logged in as #{current_author.name} "
						-if current_author.admin?
							= "(admin)"
				- else
					%li
						= link_to "Sign In", new_author_session_path
					%li 
						= link_to "Sign Up", new_author_registration_path 
		%p.flash
			= flash.notice
		= yield

app/views/static_pages/index.html.haml
%h1 Welcome to my Blogger

%h2 What you can do here...

%ul.features
	%li Create your personal article.
	%li Add other's articles to your favourites' list.
	%li Write your opinion about articles by commenting on them.
	%li Find articles by their corresponding tags.
	%li Add favourite tags to your own list.

app/views/tags/index.html.erb
<h1>Tags</h1>

<table>
	<% @tags.each do |tag| %>
	<tr class = "tag_row">
		<td style="font-size: 20px;">
			<%= link_to tag, tag_path(tag) %>
		</td>
    <% if author_signed_in? %>
    	<% unless tag.authors.include?(current_author) %>
			<td><%= button_to "Add", { action: "add_tag_to_author", id: tag.id },
																method: :put %></td>
			<% else %>													
				<td><p class="add_tag">Added</p></td>
			<% end %>
		<% end %>
		<% if author_signed_in? &&  current_author.admin? %>
			<td ><%= button_to "Delete", { :action => "destroy", :id => tag.id }, :confirm => "Are you sure?",													method: :delete %></td>
		<% end %>
	</tr>
	<% end %>
</table>

app/views/tags/show.html.erb
<h1>Articles tagged with "<%= @tag.name.capitalize %>"	</h1>
<div class="article_list">
	<ul>
		<% @tag.articles.each do |article| %>
		<li>
			<%= link_to article.title, article_path(article) %>
		</li>
		<% end %>
	</ul>
</div>	